export const paths = {
  home: "/",
  movies: "/movies",
  movie: (slug: string) => `/movies/${slug}`,
  seats: (showtimeId: string) => `/showtimes/${showtimeId}/seats`,
  checkout: (bookingId: string) => `/checkout/${bookingId}`,
  tickets: "/tickets",
  ticket: (code: string) => `/tickets/${code}`,
  notifications: "/notifications",
  login: "/login",
  loginNext: (next: string) => `/login?next=${encodeURIComponent(next)}`,
  register: "/register",
  admin: "/admin",
  adminMovies: "/admin/movies",
  adminShowtimes: "/admin/showtimes",
  adminBookings: "/admin/bookings",
  adminTickets: "/admin/tickets",
  adminUsers: "/admin/users",
} as const;
