export const paths = {
  home: "/",
  movies: "/movies",
  movie: (slug: string) => `/movies/${slug}`,
  seats: (showtimeId: string, ticket?: string) =>
    ticket
      ? `/showtimes/${showtimeId}/seats?ticket=${encodeURIComponent(ticket)}`
      : `/showtimes/${showtimeId}/seats`,
  checkout: (bookingId: string) => `/checkout/${bookingId}`,
  tickets: "/tickets",
  ticket: (code: string) => `/tickets/${code}`,
  changeShowtime: (code: string) => `/tickets/${encodeURIComponent(code)}/change`,
  gate: (code: string, sig?: string) =>
    sig ? `/gate/${encodeURIComponent(code)}?s=${encodeURIComponent(sig)}` : `/gate/${encodeURIComponent(code)}`,
  staff: "/staff",
  notifications: "/notifications",
  login: "/login",
  loginNext: (next: string) => `/login?next=${encodeURIComponent(next)}`,
  verifyEmail: "/verify-email",
  register: "/register",
  legalAgeVerification: "/legal/age-verification",
  admin: "/admin",
  adminMovies: "/admin/movies",
  adminShowtimes: "/admin/showtimes",
  adminRooms: "/admin/rooms",
  adminCinemas: "/admin/cinemas",
  adminConcessions: "/admin/concessions",
  adminReports: "/admin/reports",
  adminAgeVerifications: "/admin/age-verifications",
  adminNotifications: "/admin/notifications",
  adminSystem: "/admin/system",
  adminBookings: "/admin/bookings",
  adminTickets: "/admin/tickets",
  adminUsers: "/admin/users",
} as const;
